name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        # This will build the image. It only pushes if the event is a 'push' to main.
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            alytarek77/my-new-app:dff78d1d0e3253ffa6d799f8d13521a03aadf453
            alytarek77/my-new-app:${{ github.sha }}

  deploy:
    needs: build-test-push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_URL }}"
